---
blank_issues_enabled: false
contact_links:
  - name: 💬 I have a question or need support
    url: https://github.com/MVladislav/ansible-cis-ubuntu-2404/discussions
    about: This issue tracker is for bugs only. Please use Discussions for general questions and support.
  - name: 🚀 Feature Request
    url: https://github.com/MVladislav/ansible-cis-ubuntu-2404/discussions/new?category=feature-requests
    about: Feature requests are tracked in Discussions. Please search for existing requests and up-vote any you like.
  - name: 🔒 Report a Security Vulnerability
    url: https://github.com/MVladislav/ansible-cis-ubuntu-2404/security/advisories
    about: If you believe you have found a security vulnerability, please report it via GitHub Security Advisories.
